### ISSUE TITLE
Peer to Peer Review

### ISSUE THREAD

**Issue by Maria18000** [Alfred-KInyua/Capstone-Project-#3]
- Font should be updated to match template. (Cocogoose and Lato fonts)
 - The colors used in the template are #ec5242, #272A31 and #D3D3D3.
-  Spacing in speakers part needs to be corrected. It should align with images and on the left side.
 - Padding needs to be adjusted in Main Program section. Extra text could be removed.

**Comment by Godfrey-Alimony** [comment]
Hello my friend have you made those changes?

**Comment by Alfred-KInyua** [comment]
Yes, thanks for following up.
